Run code from exploitation zone to prepare the csvs to be used by model

In [1]:
from exploitation_zone.prepare_data import generate_meta_trsa_csv, generate_height_trsa_csv

In [3]:
generate_meta_trsa_csv(
    "trusted_zone/preprocessed_data/cleaned_catastro.geojson",
    "/Users/ceciliaperez/Documents/UPC-MD/TFM/Code/MARL-BuildingEnergyEstimation-main/data/data_config/meta_trsa2.csv"
)

       OBJECTID YearBuilt1  HEIGHT UseDescription  GrossFloorArea
0             1       1983       3              3             358
1             2       1975       3              2             119
2             3       1970       6              2             400
3             4       1940       3              1             347
4             5       1960       6              1             366
...         ...        ...     ...            ...             ...
25859     25860       1970       3              4            1738
25860     25861       1990       9              3           25681
25861     25862       1979       3              3              16
25862     25863       2006       6              3           12318
25863     25864       1967       9              4            6679

[25864 rows x 5 columns]

In [ ]:
generate_height_trsa_csv(
    "trusted_zone/preprocessed_data/cleaned_catastro.geojson",
    "/Users/ceciliaperez/Documents/UPC- MD/TFM/Code/MARL-BuildingEnergyEstimation-main/data/data_config/height_trsa.csv"
)

       OBJECTID  HEIGHT_norm
0             1            3
1             2            3
2             3            6
3             4            3
4             5            6
...         ...          ...
25859     25860            3
25860     25861            9
25861     25862            3
25862     25863            6
25863     25864            9

[25864 rows x 2 columns]

In [17]:
import pandas as pd
import os
df = pd.read_csv("../data/data_config/meta_trsa2.csv")
df_residential = df[df['UseDescription'] == '1']
df_tertiary = df[df['UseDescription'] != '1']
df_residential.to_csv("../data/data_config/residential/meta_trsa_residential.csv", index=False)
df_tertiary.to_csv("../data/data_config/tertiary/meta_trsa_tertiary.csv", index=False)

In [ ]:
df_h = pd.read_csv("../data/data_config/height_trsa.csv")

df_h_residential = df_h[df_h['OBJECTID'].isin(df_residential['OBJECTID'])]
df_h_tertiary = df_h[df_h['OBJECTID'].isin(df_tertiary['OBJECTID'])]


df_h_residential.to_csv("../data/data_config/residential/height_trsa_residential.csv", index=False)
df_h_tertiary.to_csv("../data/data_config/tertiary/height_trsa_tertiary.csv", index=False)

In [21]:
import shutil

residential_ids = pd.read_csv("../data/data_config/residential/meta_trsa_residential.csv")['OBJECTID'].astype(str).tolist()
tertiary_ids = pd.read_csv("../data/data_config/tertiary/meta_trsa_tertiary.csv")['OBJECTID'].astype(str).tolist()


source_folder = "../data/data_root_1/data02"
residential_dest = "../data/data_root_1/data_rs"
tertiary_dest = "../data/data_root_1/data_tert"


os.makedirs(residential_dest, exist_ok=True)
os.makedirs(tertiary_dest, exist_ok=True)

for filename in os.listdir(source_folder):
    if filename.endswith(".png"):
        object_id = os.path.splitext(filename)[0] 

        if object_id in residential_ids:
            shutil.copy(os.path.join(source_folder, filename), os.path.join(residential_dest, filename))
        elif object_id in tertiary_ids:
            shutil.copy(os.path.join(source_folder, filename), os.path.join(tertiary_dest, filename))